# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flashattention',
                'doc_host': 'https://xrsrke.github.io',
                'git_url': 'https://github.com/xrsrke/flashattention',
                'lib_path': 'flashattention'},
  'syms': { 'flashattention.attention': { 'flashattention.attention.Attention': ('attention.html#attention', 'flashattention/attention.py'),
                                          'flashattention.attention.Attention.__init__': ( 'attention.html#attention.__init__',
                                                                                           'flashattention/attention.py'),
                                          'flashattention.attention.Attention.forward': ( 'attention.html#attention.forward',
                                                                                          'flashattention/attention.py')}}}
